// src/db/index.ts
// Combined schema export — all tables accessible via `db` object

export { nodes } from './schema/public/nodes'
export { cells } from './schema/public/cells'
export { users } from './schema/public/users'
export { giftsProfiles } from './schema/public/gifts-profiles'
export { listings } from './schema/public/listings'
export { matches } from './schema/public/matches'
export { tradeCompletions } from './schema/public/trade-completions'
export { communityExchangeReference } from './schema/public/community-exchange-reference'
export { valueCharters } from './schema/public/value-charters'
export { grounders } from './schema/public/grounders'
export { programmeOfferings } from './schema/public/programme-offerings'
export { offeringEngagements } from './schema/public/offering-engagements'
export { offeringEndorsements } from './schema/public/offering-endorsements'
export { connectionEvents } from './schema/public/connection-events'
export { networkPhaseSnapshots } from './schema/public/network-phase-snapshots'
export { crisisMode } from './schema/public/crisis-mode'
export { externalSignals } from './schema/public/external-signals'
export { internalForecasts } from './schema/public/internal-forecasts'
export { anticipatoryAlerts } from './schema/public/anticipatory-alerts'
export { multiSignalAlerts } from './schema/public/multi-signal-alerts'
export { communityHealthAssessments } from './schema/public/community-health-assessments'
export { notificationLog } from './schema/public/notification-log'
export { cooperatives } from './schema/coop_pii/cooperatives'
export { foundingMembers } from './schema/coop_pii/founding-members'
export { cooperativeStatusEvents } from './schema/coop_pii/cooperative-status-events'
export { otpCodes } from './schema/public/otp-codes'
export { sessionTokens } from './schema/public/session-tokens'
